language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ewycheung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ewycheung/react-test npm test -- --coverage

after_success:
  - docker build -t ewycheung/multi-client ./client
  - docker build -t ewycheung/multi-nginx ./nginx
  - docker build -t ewycheung/multi-server ./server
  - docker build -t ewycheung/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and pust them to docker hub
  - docker push ewycheung/multi-client
  - docker push ewycheung/multi-nginx
  - docker push ewycheung/multi-server
  - docker push ewycheung/multi-worker